{% set name = "jsongrapher" %}
{% set version = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jsongrapher-{{ version }}.tar.gz
  sha256: 0b8fe0118a7f675ab9ad064ea01a84644c5912ac42030f59172a5d842b8f8b28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - JSONGrapher
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AdityaSavara/jsongrapher-py
  summary: The python version of JSONGrapher with tools for creating JSONGrapher Records.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdityaSavara
